# Generated by Django 3.1.3 on 2020-11-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0004_auto_20201116_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='NPC的名称')),
                ('node', models.CharField(max_length=8, verbose_name='节点编号')),
                ('type_node', models.CharField(max_length=8, verbose_name='节点类型')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc', to='block5.gender')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_type', to='block5.itemtype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc', to='block5.job')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc', to='block5.scene')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc', to='block5.team')),
            ],
            options={
                'db_table': 'node_npc',
            },
        ),
        migrations.CreateModel(
            name='NPCExtraAttrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='属性名')),
                ('value', models.CharField(max_length=16, verbose_name='属性值')),
                ('type', models.CharField(max_length=8, verbose_name='数据类型')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='block5.npcnode')),
            ],
            options={
                'db_table': 'node_npc_extra_attrs',
            },
        ),
    ]
