# Generated by Django 3.1.3 on 2020-11-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0005_npcextraattrs_npcnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcextraattrs',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='block5.npcnode'),
        ),
    ]
