# Generated by Django 3.1.3 on 2020-11-17 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0006_auto_20201116_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npcnode',
            name='item_type',
        ),
        migrations.AddField(
            model_name='npcnode',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='npc', to='block5.role'),
            preserve_default=False,
        ),
    ]
