# Generated by Django 3.1.3 on 2020-11-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0007_auto_20201117_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcnode',
            name='name',
            field=models.CharField(max_length=64, verbose_name='NPC的名称'),
        ),
        migrations.AlterField(
            model_name='npcnode',
            name='node',
            field=models.CharField(max_length=32, verbose_name='节点编号'),
        ),
        migrations.AlterField(
            model_name='npcnode',
            name='type_node',
            field=models.CharField(max_length=32, verbose_name='节点类型'),
        ),
    ]
