# Generated by Django 3.1.3 on 2020-11-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0008_auto_20201117_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='NPC的名称')),
                ('node', models.CharField(max_length=32, verbose_name='节点编号')),
                ('type_node', models.CharField(max_length=32, verbose_name='节点类型')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='block5.itemtype')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='block5.scene')),
            ],
            options={
                'db_table': 'node_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsExtraAttrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='属性名')),
                ('value', models.CharField(max_length=16, verbose_name='属性值')),
                ('type', models.CharField(max_length=8, verbose_name='数据类型')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='block5.goods')),
            ],
            options={
                'db_table': 'node_goods_extra_attrs',
            },
        ),
    ]
