# Generated by Django 3.1.3 on 2020-11-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0010_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='block5.actions'),
            preserve_default=False,
        ),
    ]
