# Generated by Django 3.1.3 on 2020-11-17 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0011_goods_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='block5.itemtype'),
        ),
    ]
