# Generated by Django 3.1.3 on 2020-11-17 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0012_auto_20201117_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='block5.goods'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='block5.actions'),
        ),
    ]
