# Generated by Django 3.1.3 on 2020-11-17 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0013_auto_20201117_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionExtraAttrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='属性名')),
                ('value', models.CharField(max_length=16, verbose_name='属性值')),
                ('type', models.CharField(max_length=8, verbose_name='数据类型')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='block5.actions')),
            ],
            options={
                'db_table': 'node_action_extra_attrs',
            },
        ),
    ]
