# Generated by Django 3.1.3 on 2020-11-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0015_actions_is_transitive_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='is_transitive_verb',
            field=models.BooleanField(default=False),
        ),
    ]
