# Generated by Django 3.1.3 on 2020-11-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0017_actioneffect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioneffect',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='af', to='block5.goods'),
        ),
        migrations.AlterField(
            model_name='actioneffect',
            name='npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='af', to='block5.npcnode'),
        ),
    ]
