# Generated by Django 3.1.3 on 2020-11-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0018_auto_20201117_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioneffect',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actioneffect',
            name='effect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NodeCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.JSONField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='block5.scene')),
            ],
            options={
                'db_table': 'node_checkout',
            },
        ),
    ]
