# Generated by Django 3.1.3 on 2020-11-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0019_auto_20201118_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecheckout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
