# Generated by Django 3.1.3 on 2020-11-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0020_nodecheckout_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodecheckout',
            name='node',
            field=models.TextField(),
        ),
    ]
