# Generated by Django 3.1.3 on 2020-11-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0021_auto_20201118_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecheckout',
            name='info',
            field=models.TextField(default=1, verbose_name='节点名称映射表'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodecheckout',
            name='node',
            field=models.TextField(verbose_name='节点图信息'),
        ),
    ]
