# Generated by Django 3.1.3 on 2020-11-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0022_auto_20201120_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.RemoveField(
            model_name='actioneffect',
            name='good',
        ),
        migrations.RemoveField(
            model_name='actioneffect',
            name='npc',
        ),
        migrations.AddField(
            model_name='goods',
            name='af',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good', to='block5.actioneffect'),
        ),
        migrations.AddField(
            model_name='npcnode',
            name='af',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npcnode', to='block5.gender'),
        ),
    ]
