# Generated by Django 3.1.3 on 2020-11-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0023_auto_20201123_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioneffect',
            name='action',
        ),
    ]
