# Generated by Django 3.1.3 on 2020-11-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0026_auto_20201123_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcnode',
            name='af_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='npcnode',
            name='af_target',
            field=models.BooleanField(default=False),
        ),
    ]
