# Generated by Django 3.1.3 on 2020-11-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0029_remove_npcnode_af_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npcnode',
            name='af_target',
        ),
        migrations.AddField(
            model_name='npcnode',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc2', to='block5.actioneffect'),
        ),
        migrations.AddField(
            model_name='npcnode',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc1', to='block5.actioneffect'),
        ),
    ]
