# Generated by Django 3.1.3 on 2020-11-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0030_auto_20201123_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcnode',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc_source', to='block5.actioneffect'),
        ),
        migrations.AlterField(
            model_name='npcnode',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc_target', to='block5.actioneffect'),
        ),
    ]
