# Generated by Django 3.1.3 on 2020-11-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block5', '0032_auto_20201123_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcnode',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc', to='block5.gender'),
        ),
        migrations.AlterField(
            model_name='npcnode',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc', to='block5.job'),
        ),
        migrations.AlterField(
            model_name='npcnode',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc', to='block5.role'),
        ),
        migrations.AlterField(
            model_name='npcnode',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc', to='block5.team'),
        ),
    ]
